Adding Pathplanner Commands
TeraViks/Thor_2023 pull request #34
Opened 2024-01-28 01:50 UTC by ILIK3T0C0D3

These commits add the pathplanner autos and paths to Thor_2023. These include the 4 note, 3 note, and the 2 note autos.

2024-01-28 02:18 UTC, ILIK3T0C0D3 commented
There are some angle issues that I am currently fixing.

2024-01-30 01:16 UTC, keira1008 requested changes

2024-01-30 01:16 UTC, keira1008 commented on src/main/java/frc/robot/subsystems/Limelight.java
> +public class Limelight extends SubsystemBase {
These are already added and fully implemented, so I don't think that this file is necessary.

2024-02-03 01:30 UTC, keira1008 approved these changes

2024-02-03 01:31 UTC, merged